import type { LifeChapterDefinition, LifeStageDefinition } from './types';

export const lifeStages: LifeStageDefinition[] = [
  {
    id: 'late_adolescence_identity',
    label: '晚期青春期：身份与独立',
    typicalAgeRange: [17, 20],
    eriksonInspiredTheme: '身份认同 vs. 角色混乱（作为叙事主题，不作为诊断或评分）',
    tasks: [
      { id: 'identity_exploration', label: '身份探索', description: '尝试不同兴趣、群体、价值与未来方向。', optional: false },
      { id: 'autonomy_from_family', label: '自主性协商', description: '在与家庭保持联系的同时形成更多自主决定。', optional: false },
      { id: 'belonging', label: '建立归属', description: '在同伴、宿舍、班级或社团中寻找归属。', optional: false },
      { id: 'education_commitment', label: '学习承诺', description: '理解专业、学习要求与自己的投入方式。', optional: false },
    ],
    notes: ['年龄范围只是常见叙事参考，不用于判断个体是否“发展正常”。'],
  },
  {
    id: 'emerging_adulthood',
    label: '成年初显期：探索与方向',
    typicalAgeRange: [18, 25],
    eriksonInspiredTheme: '身份延续与亲密关系准备',
    tasks: [
      { id: 'career_exploration', label: '职业探索', description: '实习、科研、考研、求职或其他路径探索。', optional: false },
      { id: 'intimacy', label: '亲密能力', description: '在不失去自我的情况下建立更深的关系。', optional: true },
      { id: 'education_commitment', label: '教育选择', description: '决定继续教育、转换方向或进入工作。', optional: true },
      { id: 'belonging', label: '成人关系网络', description: '形成更稳定但也更自主的社会网络。', optional: false },
    ],
    notes: ['允许不恋爱、不结婚、不生育等多种人生路径。'],
  },
  {
    id: 'early_adulthood_intimacy',
    label: '成年早期：亲密、工作与承诺',
    typicalAgeRange: [23, 35],
    eriksonInspiredTheme: '亲密 vs. 孤立（作为发展主题）',
    tasks: [
      { id: 'work_competence', label: '工作能力', description: '在真实组织中形成职业能力与工作身份。', optional: false },
      { id: 'partnership_commitment', label: '关系承诺', description: '对亲密关系、单身生活或其他关系形式形成选择。', optional: true },
      { id: 'family_formation', label: '家庭形成', description: '可能进入婚姻、同居、共同生活或其他家庭安排。', optional: true },
      { id: 'career_exploration', label: '职业方向修正', description: '跳槽、转行、深造或形成稳定职业方向。', optional: false },
    ],
    notes: ['“亲密”不仅指恋爱，也包括友谊、互赖、照护和长期承诺。'],
  },
  {
    id: 'adulthood_generativity',
    label: '成年中期：贡献与代际责任',
    typicalAgeRange: [35, 55],
    eriksonInspiredTheme: '繁衍/创造 vs. 停滞（广义 generativity）',
    tasks: [
      { id: 'generativity', label: '代际贡献', description: '通过工作、照护、教育、创造或社区活动贡献给下一代。', optional: false },
      { id: 'parenting_or_caregiving', label: '养育/照护', description: '可能承担对子女、伴侣或其他人的长期照护责任。', optional: true },
      { id: 'care_for_older_generation', label: '上一代照护', description: '面对父母变老、家庭责任与边界重新调整。', optional: true },
      { id: 'career_reappraisal', label: '职业再评价', description: '重新评估工作、意义、收入和时间投入。', optional: false },
    ],
    notes: ['generativity 不等同于生育；无子女路径同样可以有很强的代际贡献。'],
  },
  {
    id: 'later_adulthood_transition',
    label: '成年后期：角色重构',
    typicalAgeRange: [50, 70],
    eriksonInspiredTheme: '贡献延续、失去适应与退休转变',
    tasks: [
      { id: 'retirement_transition', label: '退休准备', description: '处理职业角色结束、财务与时间结构变化。', optional: false },
      { id: 'social_role_reconstruction', label: '角色重构', description: '在工作之外建立新的社会身份和日常节奏。', optional: false },
      { id: 'meaning_making', label: '意义重构', description: '重新理解成就、关系、遗憾与未来。', optional: false },
      { id: 'care_for_older_generation', label: '家庭照护变化', description: '可能面对上一代衰老、丧失与家庭角色变化。', optional: true },
    ],
    notes: ['退休年龄和路径由剧情与背景决定，不假设统一标准。'],
  },
  {
    id: 'late_life_integrity',
    label: '晚年：整合与生命回顾',
    typicalAgeRange: [65, 100],
    eriksonInspiredTheme: '自我整合 vs. 绝望（作为生命回顾主题）',
    tasks: [
      { id: 'life_review', label: '生命回顾', description: '回顾重要决定、关系、损失、成就与未完成事项。', optional: false },
      { id: 'meaning_making', label: '意义整合', description: '形成对自己人生的更完整解释。', optional: false },
      { id: 'social_role_reconstruction', label: '晚年角色', description: '维持或重建社会参与、兴趣和支持网络。', optional: false },
      { id: 'generativity', label: '经验传递', description: '通过家庭、社区、指导或创作继续产生影响。', optional: true },
    ],
    notes: ['避免把衰老单纯写成下降；保留成长、关系深化和新角色。'],
  },
];

export const lifeChapters: LifeChapterDefinition[] = [
  {
    id: 'university_first_week',
    season: 'university',
    title: '大学第一周',
    ageRange: [18, 19],
    timeScale: 'day',
    expectedPlayableUnits: 7,
    developmentalTasks: ['identity_exploration', 'autonomy_from_family', 'belonging', 'education_commitment'],
    eventPools: ['education', 'social', 'family', 'relationship'],
  },
  {
    id: 'freshman_year',
    season: 'university',
    title: '大一：适应与第一次选择',
    ageRange: [18, 20],
    timeScale: 'week',
    expectedPlayableUnits: 10,
    developmentalTasks: ['identity_exploration', 'belonging', 'education_commitment'],
    eventPools: ['education', 'exam', 'holiday', 'social', 'relationship', 'family'],
  },
  {
    id: 'sophomore_year',
    season: 'university',
    title: '大二：关系与方向',
    ageRange: [19, 21],
    timeScale: 'month',
    expectedPlayableUnits: 8,
    developmentalTasks: ['identity_exploration', 'career_exploration', 'intimacy'],
    eventPools: ['education', 'exam', 'holiday', 'relationship', 'career', 'social'],
  },
  {
    id: 'junior_year',
    season: 'university',
    title: '大三：实习、升学与未来',
    ageRange: [20, 23],
    timeScale: 'month',
    expectedPlayableUnits: 9,
    developmentalTasks: ['career_exploration', 'education_commitment', 'intimacy'],
    eventPools: ['exam', 'career', 'relationship', 'financial', 'social', 'holiday'],
  },
  {
    id: 'senior_year_graduation',
    season: 'university',
    title: '大四：毕业与离校',
    ageRange: [21, 24],
    timeScale: 'month',
    expectedPlayableUnits: 8,
    developmentalTasks: ['career_exploration', 'education_commitment', 'belonging'],
    eventPools: ['education', 'career', 'relationship', 'relocation', 'achievement', 'failure'],
  },
  {
    id: 'early_career_entry',
    season: 'early_career',
    title: '初入职场',
    ageRange: [22, 28],
    timeScale: 'quarter',
    expectedPlayableUnits: 10,
    developmentalTasks: ['work_competence', 'career_exploration', 'intimacy'],
    eventPools: ['career', 'financial', 'relationship', 'relocation', 'achievement', 'failure'],
  },
  {
    id: 'partnership_and_family_choices',
    season: 'partnership_family',
    title: '关系、家庭与长期选择',
    ageRange: [25, 38],
    timeScale: 'year',
    expectedPlayableUnits: 10,
    developmentalTasks: ['partnership_commitment', 'family_formation', 'work_competence'],
    eventPools: ['relationship', 'family', 'career', 'financial', 'health', 'relocation'],
  },
  {
    id: 'midlife_responsibility',
    season: 'midlife',
    title: '中年：责任、照护与重新选择',
    ageRange: [35, 55],
    timeScale: 'multi_year',
    expectedPlayableUnits: 9,
    developmentalTasks: ['generativity', 'parenting_or_caregiving', 'care_for_older_generation', 'career_reappraisal'],
    eventPools: ['career', 'family', 'health', 'financial', 'relationship', 'bereavement'],
  },
  {
    id: 'later_career_transition',
    season: 'later_career',
    title: '职业后期与角色变化',
    ageRange: [50, 67],
    timeScale: 'multi_year',
    expectedPlayableUnits: 7,
    developmentalTasks: ['career_reappraisal', 'retirement_transition', 'meaning_making'],
    eventPools: ['career', 'health', 'family', 'financial', 'bereavement', 'achievement'],
  },
  {
    id: 'retirement_reconstruction',
    season: 'retirement',
    title: '退休：重建日常与关系',
    ageRange: [60, 80],
    timeScale: 'multi_year',
    expectedPlayableUnits: 7,
    developmentalTasks: ['retirement_transition', 'social_role_reconstruction', 'meaning_making'],
    eventPools: ['retirement', 'health', 'family', 'social', 'relationship', 'holiday'],
  },
  {
    id: 'life_review',
    season: 'life_review',
    title: '人生回顾',
    ageRange: [70, 100],
    timeScale: 'multi_year',
    expectedPlayableUnits: 5,
    developmentalTasks: ['life_review', 'meaning_making', 'generativity'],
    eventPools: ['family', 'relationship', 'social', 'bereavement', 'achievement', 'historical_context'],
  },
];

export const getLifeStage = (id: LifeStageDefinition['id']) => lifeStages.find((stage) => stage.id === id);
export const getLifeChapter = (id: string) => lifeChapters.find((chapter) => chapter.id === id);
