import type { CampusScenario } from './types';

export const campusScenarios: CampusScenario[] = [
  {
    id: 'club_recruitment_01',
    title: '社团招新',
    location: 'student_center',
    ordinaryGoal: '了解几个社团并决定是否加入。',
    setup: '活动中心同时有几个社团在招新，同学邀请玩家一起逛摊位。',
    npcRoles: ['club_member', 'classmate'],
    hiddenTargets: ['big5.extraversion', 'big5.openness'],
    safetyLevel: 'ordinary',
    researchUse: 'behavioral_feature',
    observableFeatures: [
      'initiates_conversation',
      'number_of_new_contacts',
      'explores_unfamiliar_options',
      'returns_to_previous_option',
    ],
  },
  {
    id: 'group_project_01',
    title: '小组作业分工',
    location: 'library',
    ordinaryGoal: '和三名同学完成课程展示分工。',
    setup: '一名组员准备不足，距离汇报还有两天，大家需要重新分配任务。',
    npcRoles: ['teammate', 'class_representative'],
    hiddenTargets: ['big5.conscientiousness', 'big5.agreeableness'],
    safetyLevel: 'ordinary',
    researchUse: 'behavioral_feature',
    observableFeatures: [
      'plans_before_acting',
      'offers_help',
      'negotiates_role',
      'confronts_teammate',
      'task_follow_up_count',
    ],
  },
  {
    id: 'roommate_rules_01',
    title: '宿舍作息协调',
    location: 'dormitory',
    ordinaryGoal: '和室友商量熄灯、空调与清洁安排。',
    setup: '两名室友的作息不同，需要共同决定宿舍规则。',
    npcRoles: ['roommate_early', 'roommate_late'],
    hiddenTargets: ['big5.agreeableness', 'big5.conscientiousness'],
    safetyLevel: 'ordinary',
    researchUse: 'behavioral_feature',
    observableFeatures: [
      'compromise_attempts',
      'boundary_setting',
      'proposes_shared_plan',
      'withdraws_from_discussion',
    ],
  },
  {
    id: 'schedule_change_01',
    title: '临时换教室',
    location: 'siyuan_building',
    ordinaryGoal: '找到临时变更后的教室并按时上课。',
    setup: '课程群临时通知换教室，不同同学给出了略有差异的信息。',
    npcRoles: ['classmate', 'class_representative'],
    hiddenTargets: ['big5.neuroticism', 'big5.conscientiousness'],
    safetyLevel: 'ordinary',
    researchUse: 'behavioral_feature',
    observableFeatures: [
      'information_check_count',
      'asks_for_confirmation',
      'route_changes',
      'response_latency',
      'recovers_after_resolution',
    ],
  },
  {
    id: 'group_chat_ambiguity_01',
    title: '群聊里的模糊消息',
    location: 'cafeteria',
    ordinaryGoal: '和同学吃饭并处理课程群里的新消息。',
    setup: '课程群出现一句没有点名的抱怨，几位同学对它在说谁有不同看法。',
    npcRoles: ['friend', 'classmate'],
    hiddenTargets: ['cape.persecutory_ideation'],
    safetyLevel: 'mild_stress',
    researchUse: 'exploratory_only',
    observableFeatures: [
      'self_referential_interpretation',
      'certainty_before_evidence',
      'seeks_social_verification',
      'checks_original_context',
      'belief_revision_after_clarification',
    ],
  },
  {
    id: 'misheard_name_01',
    title: '好像听见有人叫你',
    location: 'library',
    ordinaryGoal: '继续完成自习任务。',
    setup: '安静环境里远处有人说话，声音像是提到了玩家名字，也可能只是相近发音。',
    npcRoles: ['study_partner'],
    hiddenTargets: ['cape.perceptual_abnormalities'],
    safetyLevel: 'mild_stress',
    researchUse: 'exploratory_only',
    observableFeatures: [
      'checks_source',
      'certainty_before_checking',
      'asks_other_person',
      'returns_to_task',
      'repeated_checking',
    ],
  },
  {
    id: 'campus_drill_01',
    title: '校园安全演练',
    location: 'dormitory',
    ordinaryGoal: '按通知参加一次常规校园安全演练。',
    setup: '宿舍楼按计划进行安全演练，广播和提示音比平时更响。',
    npcRoles: ['roommate', 'student_helper'],
    hiddenTargets: ['pcl5_associated.arousal_reactivity'],
    safetyLevel: 'sensitive',
    researchUse: 'exploratory_only',
    observableFeatures: [
      'startle_related_behavior',
      'leaves_area',
      'reassurance_seeking',
      'time_to_resume_activity',
    ],
  },
  {
    id: 'presentation_reminder_01',
    title: '汇报前的提醒',
    location: 'siyuan_building',
    ordinaryGoal: '完成课堂展示。',
    setup: '老师临时提醒展示顺序提前，玩家需要决定继续准备、求助同学还是先离开现场。',
    npcRoles: ['teacher', 'teammate'],
    hiddenTargets: ['big5.neuroticism', 'pcl5_associated.avoidance'],
    safetyLevel: 'mild_stress',
    researchUse: 'exploratory_only',
    observableFeatures: [
      'approach_or_avoid',
      'asks_for_support',
      'task_persistence',
      'response_latency',
      'returns_after_leaving',
    ],
  },
];

export const getCampusScenario = (id: string) => campusScenarios.find((scenario) => scenario.id === id);
