import { defineContentPack } from '../types';

export const campusLifePack = defineContentPack({
  id: 'campus-life',
  title: '大学日常',
  description: '高频、低压力、跨学校成立的普通大学生活内容，作为世界主体验与行为基线。',
  scope: 'campus',
  status: 'enabled',
  scenarios: [
    {
      id: 'breakfast_routine_01',
      title: '早餐时间',
      packId: 'campus-life',
      location: 'cafeteria',
      ordinaryGoal: '吃完早餐，再决定上午怎么安排。',
      setup: '食堂正是早餐高峰，同学们陆续赶来。今天没有特别任务，只是一顿普通早餐。',
      estimatedMinutes: 30,
      npcRoles: ['classmate', 'roommate'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['routine', 'food', 'pure-life'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [1, 2, 5] },
    },
    {
      id: 'library_browse_01',
      title: '在图书馆随便逛逛',
      packId: 'campus-life',
      location: 'library',
      ordinaryGoal: '找个位置，看看书或处理自己的事情。',
      setup: '暂时没有迫在眉睫的任务。图书馆里有人复习、聊天，也有人只是找个安静角落待一会儿。',
      estimatedMinutes: 30,
      npcRoles: ['classmate', 'study_partner'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['routine', 'study', 'pure-life'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [2, 3, 7] },
    },
    {
      id: 'campus_walk_01',
      title: '校园里走一圈',
      packId: 'campus-life',
      location: 'campus_green',
      ordinaryGoal: '在校园公共空间休息一会儿。',
      setup: '天气还不错，下一件事也不急。你可以散步、坐着发呆，或者和碰到的熟人聊几句。',
      estimatedMinutes: 30,
      npcRoles: ['friend', 'classmate'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['leisure', 'routine', 'pure-life'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [1, 4, 7] },
    },
    {
      id: 'dorm_room_reset_01',
      title: '整理一下住处',
      packId: 'campus-life',
      location: 'dormitory',
      ordinaryGoal: '把自己的东西收拾好，再安排晚上的事。',
      setup: '桌面有点乱，衣服和快递盒堆在一边。室友各忙各的，没有冲突，也没有隐藏任务。',
      estimatedMinutes: 25,
      npcRoles: ['roommate'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['dormitory', 'routine', 'pure-life'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [1, 5, 7] },
    },
    {
      id: 'casual_sports_01',
      title: '去运动一下',
      packId: 'campus-life',
      location: 'sports_field',
      ordinaryGoal: '活动一下身体，想什么时候结束都可以。',
      setup: '运动场有人跑步，也有人随便打球。你可以参加、旁观或按自己的节奏运动。',
      estimatedMinutes: 45,
      npcRoles: ['friend', 'classmate'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['sports', 'leisure', 'pure-life'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [4, 6] },
    },
    {
      id: 'meet_at_gate_01',
      title: '校门口等人',
      packId: 'campus-life',
      location: 'campus_gate',
      ordinaryGoal: '和约好的人碰面，再一起去下一站。',
      setup: '你比约定时间早到了一点。校门附近人来人往，今天只是一次普通的会合。',
      estimatedMinutes: 20,
      npcRoles: ['friend', 'classmate'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['arrival', 'social', 'pure-life'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [1, 6] },
    },
    {
      id: 'club_recruitment_01',
      title: '社团招新',
      packId: 'campus-life',
      location: 'student_center',
      ordinaryGoal: '了解几个社团并决定是否加入。',
      setup: '学生活动区域同时有几个社团在招新，同学邀请玩家一起逛摊位。',
      estimatedMinutes: 45,
      npcRoles: ['club_member', 'classmate'],
      hiddenTargets: ['big5.extraversion', 'big5.openness'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'initiates_conversation',
        'number_of_new_contacts',
        'explores_unfamiliar_options',
        'returns_to_previous_option',
      ],
      tags: ['social', 'exploration', 'clubs'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [4] },
    },
    {
      id: 'group_project_01',
      title: '小组作业分工',
      packId: 'campus-life',
      location: 'library',
      ordinaryGoal: '和三名同学完成课程展示分工。',
      setup: '一名组员准备不足，距离汇报还有两天，大家需要重新分配任务。',
      estimatedMinutes: 45,
      npcRoles: ['teammate', 'class_representative'],
      hiddenTargets: [
        'big5.conscientiousness',
        'big5.agreeableness',
        'coping.problem_focused',
      ],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'plans_before_acting',
        'offers_help',
        'negotiates_role',
        'confronts_teammate',
        'task_follow_up_count',
      ],
      tags: ['study', 'cooperation', 'planning'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [3] },
    },
    {
      id: 'schedule_change_01',
      title: '临时换教室',
      packId: 'campus-life',
      location: 'teaching_building',
      ordinaryGoal: '找到临时变更后的教室并按时上课。',
      setup: '课程群临时通知换教室，不同同学给出了略有差异的信息。',
      estimatedMinutes: 25,
      npcRoles: ['classmate', 'class_representative'],
      hiddenTargets: [
        'big5.neuroticism',
        'big5.conscientiousness',
        'coping.problem_focused',
      ],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'information_check_count',
        'asks_for_confirmation',
        'route_changes',
        'response_latency',
        'recovers_after_resolution',
      ],
      tags: ['study', 'uncertainty', 'time-pressure'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [2] },
    },
    {
      id: 'presentation_reminder_01',
      title: '汇报顺序提前',
      packId: 'campus-life',
      location: 'teaching_building',
      ordinaryGoal: '完成课堂展示。',
      setup: '老师临时提醒展示顺序提前，玩家需要决定继续准备、求助同学还是调整计划。',
      estimatedMinutes: 45,
      npcRoles: ['teacher', 'teammate'],
      hiddenTargets: ['big5.neuroticism', 'coping.problem_focused', 'social.support_seeking'],
      safetyLevel: 'mild_stress',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'asks_for_support',
        'task_persistence',
        'response_latency',
        'plan_revision_count',
        'time_to_resume_task',
      ],
      tags: ['study', 'evaluation', 'time-pressure'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [3, 5] },
    },
  ],
});
