import { defineContentPack } from '../types';

export const campusLifePack = defineContentPack({
  id: 'campus-life',
  title: '大学日常',
  description: '高频、低压力、跨学校成立的普通大学生活内容，作为世界主体验与行为基线。',
  scope: 'campus',
  status: 'enabled',
  scenarios: [
    {
      id: 'club_recruitment_01',
      title: '社团招新',
      packId: 'campus-life',
      location: 'student_center',
      ordinaryGoal: '了解几个社团并决定是否加入。',
      setup: '学生活动区域同时有几个社团在招新，同学邀请玩家一起逛摊位。',
      npcRoles: ['club_member', 'classmate'],
      hiddenTargets: ['big5.extraversion', 'big5.openness'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'initiates_conversation',
        'number_of_new_contacts',
        'explores_unfamiliar_options',
        'returns_to_previous_option',
      ],
      tags: ['social', 'exploration', 'clubs'],
      enabledByDefault: true,
    },
    {
      id: 'group_project_01',
      title: '小组作业分工',
      packId: 'campus-life',
      location: 'library',
      ordinaryGoal: '和三名同学完成课程展示分工。',
      setup: '一名组员准备不足，距离汇报还有两天，大家需要重新分配任务。',
      npcRoles: ['teammate', 'class_representative'],
      hiddenTargets: [
        'big5.conscientiousness',
        'big5.agreeableness',
        'coping.problem_focused',
      ],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'plans_before_acting',
        'offers_help',
        'negotiates_role',
        'confronts_teammate',
        'task_follow_up_count',
      ],
      tags: ['study', 'cooperation', 'planning'],
      enabledByDefault: true,
    },
    {
      id: 'schedule_change_01',
      title: '临时换教室',
      packId: 'campus-life',
      location: 'teaching_building',
      ordinaryGoal: '找到临时变更后的教室并按时上课。',
      setup: '课程群临时通知换教室，不同同学给出了略有差异的信息。',
      npcRoles: ['classmate', 'class_representative'],
      hiddenTargets: [
        'big5.neuroticism',
        'big5.conscientiousness',
        'coping.problem_focused',
      ],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'information_check_count',
        'asks_for_confirmation',
        'route_changes',
        'response_latency',
        'recovers_after_resolution',
      ],
      tags: ['study', 'uncertainty', 'time-pressure'],
      enabledByDefault: true,
    },
    {
      id: 'presentation_reminder_01',
      title: '汇报顺序提前',
      packId: 'campus-life',
      location: 'teaching_building',
      ordinaryGoal: '完成课堂展示。',
      setup: '老师临时提醒展示顺序提前，玩家需要决定继续准备、求助同学还是调整计划。',
      npcRoles: ['teacher', 'teammate'],
      hiddenTargets: ['big5.neuroticism', 'coping.problem_focused', 'social.support_seeking'],
      safetyLevel: 'mild_stress',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'asks_for_support',
        'task_persistence',
        'response_latency',
        'plan_revision_count',
        'time_to_resume_task',
      ],
      tags: ['study', 'evaluation', 'time-pressure'],
      enabledByDefault: true,
    },
  ],
});
