import { defineContentPack } from '../types';

export const cityLifePack = defineContentPack({
  id: 'city-life',
  title: '校外生活',
  description: '把大学生活延伸到聚餐、KTV、通勤、实习、旅行等校外活动；地点可先作为计划内容，后续再接独立地图。',
  scope: 'city',
  status: 'planned',
  scenarios: [
    {
      id: 'dinner_cancellation_01',
      title: '聚餐临时少了两个人',
      packId: 'city-life',
      location: 'restaurant',
      ordinaryGoal: '和朋友完成一次普通聚餐。',
      setup: '原本约了五个人，其中两个人在出发前临时说来不了，剩下的人对是否继续聚餐意见不同。',
      npcRoles: ['friend', 'classmate', 'late_canceller'],
      hiddenTargets: [
        'social.rejection_sensitivity',
        'social.trust',
        'emotion.regulation',
        'coping.problem_focused',
      ],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'continues_plan',
        'asks_reason_for_cancellation',
        'attributes_cancellation_personally',
        'reorganizes_group',
        'future_invitation_change',
      ],
      tags: ['friends', 'dining', 'plan-change'],
      enabledByDefault: false,
    },
    {
      id: 'ktv_song_pressure_01',
      title: '聚会里被起哄唱歌',
      packId: 'city-life',
      location: 'ktv',
      ordinaryGoal: '参加朋友生日聚会。',
      setup: '大家起哄让玩家唱一首歌，其中一个人持续催促，但也有人说“不想唱也没事”。',
      npcRoles: ['friend', 'pushy_friend', 'supportive_friend'],
      hiddenTargets: ['big5.extraversion', 'emotion.regulation', 'social.support_seeking'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'accepts_spotlight',
        'declines_directly',
        'uses_humor_to_decline',
        'seeks_ally',
        'stays_at_event',
      ],
      tags: ['party', 'peer-pressure', 'social'],
      enabledByDefault: false,
    },
    {
      id: 'transit_delay_01',
      title: '地铁延误',
      packId: 'city-life',
      location: 'transit_hub',
      ordinaryGoal: '按计划到达约定地点。',
      setup: '出发后遇到明显延误，朋友已经到了，地图上有几条时间与费用不同的替代路线。',
      npcRoles: ['friend_remote'],
      hiddenTargets: [
        'big5.conscientiousness',
        'coping.problem_focused',
        'decision.risk_taking',
      ],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'checks_alternative_routes',
        'notifies_waiting_person',
        'changes_route',
        'accepts_higher_cost_option',
        'decision_latency',
      ],
      tags: ['transit', 'delay', 'decision'],
      enabledByDefault: false,
    },
    {
      id: 'internship_feedback_01',
      title: '实习反馈不太客气',
      packId: 'city-life',
      location: 'internship_office',
      ordinaryGoal: '根据反馈修改一份实习任务。',
      setup: '带教给出的修改意见有实际内容，但措辞比较生硬；同组实习生对这位带教评价也不一致。',
      npcRoles: ['supervisor', 'intern_peer'],
      hiddenTargets: [
        'emotion.regulation',
        'emotion.reappraisal',
        'coping.problem_focused',
        'social.support_seeking',
      ],
      safetyLevel: 'mild_stress',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'separates_content_from_tone',
        'asks_clarifying_question',
        'seeks_peer_support',
        'revises_work',
        'withdraws_from_task',
      ],
      tags: ['internship', 'feedback', 'evaluation'],
      enabledByDefault: false,
    },
  ],
});
