import { defineContentPack } from '../types';

export const lifeCoursePack = defineContentPack({
  id: 'life-course',
  title: '长期人生历程',
  description: '从毕业、实习和工作延伸到长期关系、家庭照护、退休与生命回顾的 planned 内容。',
  scope: 'mixed',
  status: 'planned',
  scenarios: [
    {
      id: 'graduation_last_walk_01',
      title: '毕业前最后一次走过校园',
      packId: 'life-course',
      location: 'campus_gate',
      ordinaryGoal: '和熟悉的人告别，决定毕业后保持哪些联系。',
      setup: '毕业手续基本完成，几位相处多年的同学准备离校。有人约你一起再走一遍校园。',
      estimatedMinutes: 60,
      npcRoles: ['close_friend', 'classmate', 'roommate'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['graduation', 'friendship', 'transition'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['university'],
        chapterIds: ['senior_year_graduation'],
        minimumAge: 20,
      },
    },
    {
      id: 'internship_first_feedback_01',
      title: '第一次实习反馈',
      packId: 'life-course',
      location: 'internship_office',
      ordinaryGoal: '理解反馈并决定接下来一周怎么调整工作。',
      setup: '带教指出几个需要修改的地方，同时肯定了其中一部分工作。你需要安排接下来的任务。',
      estimatedMinutes: 45,
      npcRoles: ['supervisor', 'intern_peer'],
      hiddenTargets: ['coping.problem_focused', 'emotion.reappraisal', 'social.support_seeking'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: ['asks_for_clarification', 'plan_revision', 'seeks_peer_support', 'returns_to_task'],
      tags: ['internship', 'feedback', 'career'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['university', 'early_career'],
        careerStages: ['internship', 'early_career'],
        developmentalTasks: ['career_exploration', 'work_competence'],
      },
    },
    {
      id: 'first_job_offer_01',
      title: '第一份工作要不要接',
      packId: 'life-course',
      location: 'family_home',
      ordinaryGoal: '在期限前决定是否接受工作机会。',
      setup: '一份工作比较稳定但地点和方向并不完全理想，另一条路径更不确定。家人和朋友给出了不同意见。',
      estimatedMinutes: 60,
      npcRoles: ['parent', 'friend', 'mentor'],
      hiddenTargets: ['decision.risk_taking', 'coping.problem_focused', 'social.support_seeking'],
      safetyLevel: 'mild_stress',
      researchUse: 'behavioral_feature',
      observableFeatures: ['compares_options', 'seeks_information', 'weighs_family_input', 'decision_latency'],
      tags: ['career', 'decision', 'family'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['university', 'early_career'],
        careerStages: ['job_search', 'early_career'],
        developmentalTasks: ['career_exploration', 'work_competence'],
      },
    },
    {
      id: 'move_in_together_01',
      title: '要不要一起住',
      packId: 'life-course',
      location: 'family_home',
      ordinaryGoal: '和伴侣讨论是否共同生活以及具体边界。',
      setup: '关系已经持续一段时间，对方提出一起住。双方需要讨论空间、金钱、家务和独处时间。',
      estimatedMinutes: 75,
      npcRoles: ['romantic_partner'],
      hiddenTargets: ['attachment.anxiety', 'attachment.avoidance', 'emotion.regulation'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: ['states_boundary', 'asks_partner_preference', 'negotiates_shared_rules', 'withdraws_from_discussion'],
      tags: ['relationship', 'cohabitation', 'boundaries'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['early_career', 'partnership_family'],
        relationshipTypes: ['romantic_partner', 'spouse'],
        developmentalTasks: ['intimacy', 'partnership_commitment'],
        minimumAge: 20,
      },
    },
    {
      id: 'long_term_commitment_01',
      title: '长期关系的下一步',
      packId: 'life-course',
      location: 'restaurant',
      ordinaryGoal: '讨论未来几年希望怎样生活。',
      setup: '你和重要伴侣有了一次难得的长谈：要不要结婚、是否保持现在的关系形式、是否要孩子、住在哪里，都可以被讨论，也都可以暂时没有答案。',
      estimatedMinutes: 90,
      npcRoles: ['romantic_partner'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['relationship', 'commitment', 'future'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['early_career', 'partnership_family'],
        relationshipTypes: ['romantic_partner', 'spouse'],
        developmentalTasks: ['partnership_commitment', 'family_formation'],
      },
    },
    {
      id: 'caregiving_parent_01',
      title: '父母开始需要更多帮助',
      packId: 'life-course',
      location: 'family_home',
      ordinaryGoal: '和家人安排一件长期照护事务。',
      setup: '父母中的一人开始在日常生活、就医或事务处理上需要更多支持。家庭成员对怎样分工意见不同。',
      estimatedMinutes: 90,
      npcRoles: ['parent', 'sibling', 'spouse'],
      hiddenTargets: ['coping.problem_focused', 'emotion.regulation', 'social.support_seeking'],
      safetyLevel: 'mild_stress',
      researchUse: 'behavioral_feature',
      observableFeatures: ['negotiates_care_roles', 'seeks_external_resources', 'sets_limit', 'requests_support'],
      tags: ['family', 'caregiving', 'midlife'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['midlife', 'later_career'],
        developmentalTasks: ['care_for_older_generation', 'generativity'],
        minimumAge: 30,
      },
    },
    {
      id: 'retirement_first_week_01',
      title: '退休后的第一周',
      packId: 'life-course',
      location: 'city_park',
      ordinaryGoal: '安排一个没有工作日程的普通星期。',
      setup: '正式离开长期工作后，早晨突然没有会议、通勤和待办。你可以重新安排运动、朋友、家庭、兴趣或只是休息。',
      estimatedMinutes: 120,
      npcRoles: ['spouse', 'friend', 'former_coworker', 'community_member'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['retirement', 'routine', 'identity'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['retirement'],
        careerStages: ['retired'],
        developmentalTasks: ['retirement_transition', 'social_role_reconstruction'],
      },
    },
    {
      id: 'life_review_reunion_01',
      title: '很多年后的重逢',
      packId: 'life-course',
      location: 'city_park',
      ordinaryGoal: '和一个认识很多年的旧朋友聊一下午。',
      setup: '多年未见的重要朋友再次来到同一座城市。对话会自然回到大学、工作、家庭、失去的人和当年没有走的路。',
      estimatedMinutes: 180,
      npcRoles: ['old_friend'],
      hiddenTargets: [],
      safetyLevel: 'ordinary',
      researchUse: 'none',
      observableFeatures: [],
      tags: ['life-review', 'friendship', 'meaning'],
      enabledByDefault: false,
      lifeContext: {
        seasons: ['retirement', 'life_review'],
        developmentalTasks: ['meaning_making', 'life_review'],
        minimumAge: 60,
      },
    },
  ],
});
