import { defineContentPack } from '../types';

export const sensitiveResearchPack = defineContentPack({
  id: 'sensitive-research',
  title: '敏感研究情境',
  description: '与 CAPE-P15 / PCL-5 相关构念的探索性场景。默认不启用，需独立研究方案、知情同意和风险处置流程。',
  scope: 'campus',
  status: 'planned',
  scenarios: [
    {
      id: 'misheard_name_01',
      title: '好像听见有人叫你',
      packId: 'sensitive-research',
      location: 'library',
      ordinaryGoal: '继续完成自习任务。',
      setup: '安静环境里远处有人说话，声音像是提到了玩家名字，也可能只是相近发音。',
      estimatedMinutes: 20,
      npcRoles: ['study_partner'],
      hiddenTargets: ['cape.perceptual_abnormalities'],
      safetyLevel: 'mild_stress',
      researchUse: 'exploratory_only',
      observableFeatures: [
        'checks_source',
        'certainty_before_checking',
        'asks_other_person',
        'returns_to_task',
        'repeated_checking',
      ],
      tags: ['ambiguity', 'perception', 'research-only'],
      enabledByDefault: false,
    },
    {
      id: 'campus_drill_01',
      title: '校园安全演练',
      packId: 'sensitive-research',
      location: 'dormitory',
      ordinaryGoal: '按通知参加一次常规校园安全演练。',
      setup: '学生住宿区按计划进行安全演练，广播和提示音比平时更响。',
      estimatedMinutes: 30,
      npcRoles: ['roommate', 'student_helper'],
      hiddenTargets: ['pcl5_associated.arousal_reactivity'],
      safetyLevel: 'sensitive',
      researchUse: 'exploratory_only',
      observableFeatures: [
        'startle_related_behavior',
        'leaves_area',
        'reassurance_seeking',
        'time_to_resume_activity',
      ],
      tags: ['safety-drill', 'arousal', 'research-only'],
      enabledByDefault: false,
    },
    {
      id: 'stressful_reminder_01',
      title: '与个人经历有关的提醒',
      packId: 'sensitive-research',
      location: 'campus_green',
      ordinaryGoal: '完成一次可随时退出的研究任务。',
      setup: '只有在独立研究方案明确规定、参与者已知情同意且有退出/转介机制时，才允许使用与真实经历有关的个体化提醒。默认实现不提供任何具体刺激。',
      estimatedMinutes: 30,
      npcRoles: ['research_facilitator'],
      hiddenTargets: ['pcl5_associated.intrusion', 'pcl5_associated.avoidance'],
      safetyLevel: 'sensitive',
      researchUse: 'exploratory_only',
      observableFeatures: [
        'task_opt_out',
        'approach_or_avoid',
        'support_request',
        'time_to_resume_neutral_activity',
      ],
      tags: ['placeholder', 'trauma-associated', 'research-only'],
      enabledByDefault: false,
    },
  ],
});
