import { defineContentPack } from '../types';

export const socialFrictionPack = defineContentPack({
  id: 'social-friction',
  title: '人际摩擦',
  description: '把讨厌的人、失约、阴阳怪气、分工不公和边界冲突作为现实校园生活的一部分，而不是病理化 NPC。',
  scope: 'campus',
  status: 'enabled',
  scenarios: [
    {
      id: 'roommate_rules_01',
      title: '宿舍作息协调',
      packId: 'social-friction',
      location: 'dormitory',
      ordinaryGoal: '和室友商量熄灯、空调与清洁安排。',
      setup: '两名室友的作息不同，其中一人说话比较强势，大家需要共同决定宿舍规则。',
      estimatedMinutes: 35,
      timeWindows: [{ start: '19:30', end: '22:45', label: '晚间宿舍协调' }],
      npcRoles: ['roommate_early', 'roommate_late'],
      hiddenTargets: ['big5.agreeableness', 'big5.conscientiousness', 'emotion.regulation'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'compromise_attempts',
        'boundary_setting',
        'proposes_shared_plan',
        'withdraws_from_discussion',
        'tone_escalation',
      ],
      tags: ['roommate', 'boundary', 'conflict'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [5, 7] },
    },
    {
      id: 'group_chat_ambiguity_01',
      title: '群聊里的模糊抱怨',
      packId: 'social-friction',
      location: 'cafeteria',
      ordinaryGoal: '和同学吃饭并处理课程群里的新消息。',
      setup: '课程群出现一句没有点名的抱怨，几位同学对它在说谁有不同看法。',
      estimatedMinutes: 20,
      timeWindows: [
        { start: '11:30', end: '14:30', label: '午饭时段' },
        { start: '17:00', end: '19:30', label: '晚饭时段' },
      ],
      npcRoles: ['friend', 'classmate'],
      hiddenTargets: [
        'cape.persecutory_ideation',
        'social.rejection_sensitivity',
        'emotion.reappraisal',
      ],
      safetyLevel: 'mild_stress',
      researchUse: 'exploratory_only',
      observableFeatures: [
        'self_referential_interpretation',
        'certainty_before_evidence',
        'seeks_social_verification',
        'checks_original_context',
        'belief_revision_after_clarification',
      ],
      tags: ['group-chat', 'ambiguity', 'peer-relations'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [5] },
    },
    {
      id: 'group_credit_01',
      title: '汇报署名争议',
      packId: 'social-friction',
      location: 'library',
      ordinaryGoal: '完成小组汇报并确认最终署名与分工说明。',
      setup: '一名贡献较少的组员在群里暗示自己承担了大部分工作，其他人反应不一。',
      estimatedMinutes: 40,
      timeWindows: [{ start: '13:00', end: '21:30', label: '小组任务时段' }],
      npcRoles: ['teammate_dominant', 'teammate_quiet', 'classmate'],
      hiddenTargets: [
        'big5.agreeableness',
        'social.trust',
        'emotion.regulation',
        'coping.problem_focused',
      ],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'confronts_claim',
        'collects_evidence',
        'seeks_group_consensus',
        'sets_boundary',
        'escalates_to_teacher',
      ],
      tags: ['group-work', 'fairness', 'conflict'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [5] },
    },
    {
      id: 'queue_cutting_01',
      title: '食堂插队',
      packId: 'social-friction',
      location: 'cafeteria',
      ordinaryGoal: '买到午饭并按原计划和朋友汇合。',
      setup: '排队时一名认识但不熟的同学直接站到前面，还笑着说“帮我占一下呗”。',
      estimatedMinutes: 15,
      timeWindows: [
        { start: '11:30', end: '14:00', label: '午饭高峰' },
        { start: '17:00', end: '19:30', label: '晚饭高峰' },
      ],
      npcRoles: ['pushy_classmate', 'friend', 'student_bystander'],
      hiddenTargets: ['big5.agreeableness', 'emotion.regulation', 'social.trust'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'asserts_boundary',
        'allows_cutting',
        'uses_humor',
        'seeks_bystander_support',
        'interaction_duration',
      ],
      tags: ['daily-life', 'boundary', 'annoyance'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [5, 6] },
    },
    {
      id: 'excluded_meetup_01',
      title: '没被叫上的聚会',
      packId: 'social-friction',
      location: 'dormitory',
      ordinaryGoal: '安排自己的晚上并处理朋友发来的消息。',
      setup: '玩家从朋友圈看到几个熟悉同学正在聚餐，之前没有人邀请自己；稍后其中一人私聊问明天是否一起上课。',
      estimatedMinutes: 25,
      timeWindows: [{ start: '18:00', end: '22:30', label: '晚间宿舍时间' }],
      npcRoles: ['friend', 'classmate'],
      hiddenTargets: [
        'social.rejection_sensitivity',
        'social.trust',
        'emotion.reappraisal',
        'big5.neuroticism',
      ],
      safetyLevel: 'mild_stress',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'assumes_intentional_exclusion',
        'asks_for_context',
        'withdraws_from_future_contact',
        'responds_to_next_day_invitation',
        'time_to_resume_activity',
      ],
      tags: ['friendship', 'social-media', 'rejection'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [6, 7] },
    },
    {
      id: 'borrowed_item_01',
      title: '借走东西一直不还',
      packId: 'social-friction',
      location: 'dormitory',
      ordinaryGoal: '拿回自己明天要用的物品。',
      setup: '同学几天前借走一件常用物品，已经两次说“晚上还”，但现在仍没送回来。',
      estimatedMinutes: 20,
      timeWindows: [{ start: '18:00', end: '22:30', label: '晚间宿舍时间' }],
      npcRoles: ['unreliable_classmate', 'roommate'],
      hiddenTargets: ['social.trust', 'big5.agreeableness', 'emotion.regulation'],
      safetyLevel: 'ordinary',
      researchUse: 'behavioral_feature',
      observableFeatures: [
        'reminder_count',
        'sets_deadline',
        'offers_alternative',
        'expresses_annoyance',
        'changes_future_lending_behavior',
      ],
      tags: ['friendship', 'boundary', 'reliability'],
      enabledByDefault: true,
      lifeContext: { firstWeekDays: [5, 7] },
    },
  ],
});
